module.exports = [
  {
    DateTime: "2018-09-29T09:00:00-04:00",
    EpochDateTime: 1538226000,
    WeatherIcon: 2,
    IconPhrase: "Mostly sunny",
    IsDaylight: true,
    Temperature: { Value: 53.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 50.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 47.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 40.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 261, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 63,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 32600.0, Unit: "ft", UnitType: 0 },
    UVIndex: 2,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 28,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=9&lang=en-us"
  },
  {
    DateTime: "2018-09-29T10:00:00-04:00",
    EpochDateTime: 1538229600,
    WeatherIcon: 3,
    IconPhrase: "Partly sunny",
    IsDaylight: true,
    Temperature: { Value: 55.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 54.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 47.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 39.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 9.2, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 267, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 56,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 33300.0, Unit: "ft", UnitType: 0 },
    UVIndex: 2,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 48,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=10&lang=en-us"
  },
  {
    DateTime: "2018-09-29T11:00:00-04:00",
    EpochDateTime: 1538233200,
    WeatherIcon: 4,
    IconPhrase: "Intermittent clouds",
    IsDaylight: true,
    Temperature: { Value: 56.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 55.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 47.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 38.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 8.1, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 273, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 49,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 4800.0, Unit: "ft", UnitType: 0 },
    UVIndex: 2,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 69,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=11&lang=en-us"
  },
  {
    DateTime: "2018-09-29T12:00:00-04:00",
    EpochDateTime: 1538236800,
    WeatherIcon: 6,
    IconPhrase: "Mostly cloudy",
    IsDaylight: true,
    Temperature: { Value: 57.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 57.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 47.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 36.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 8.1, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 270, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 9.2, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 45,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 4600.0, Unit: "ft", UnitType: 0 },
    UVIndex: 2,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 75,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=12&lang=en-us"
  },
  {
    DateTime: "2018-09-29T13:00:00-04:00",
    EpochDateTime: 1538240400,
    WeatherIcon: 6,
    IconPhrase: "Mostly cloudy",
    IsDaylight: true,
    Temperature: { Value: 58.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 58.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 47.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 36.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 8.1, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 260, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 43,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 5000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 2,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 82,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=13&lang=en-us"
  },
  {
    DateTime: "2018-09-29T14:00:00-04:00",
    EpochDateTime: 1538244000,
    WeatherIcon: 6,
    IconPhrase: "Mostly cloudy",
    IsDaylight: true,
    Temperature: { Value: 59.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 58.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 48.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 36.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 8.1, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 253, Localized: "WSW", English: "WSW" }
    },
    WindGust: { Speed: { Value: 11.5, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 43,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 5000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 1,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 88,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=14&lang=en-us"
  },
  {
    DateTime: "2018-09-29T15:00:00-04:00",
    EpochDateTime: 1538247600,
    WeatherIcon: 6,
    IconPhrase: "Mostly cloudy",
    IsDaylight: true,
    Temperature: { Value: 61.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 59.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 49.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 39.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 257, Localized: "WSW", English: "WSW" }
    },
    WindGust: { Speed: { Value: 12.7, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 45,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 5000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 1,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 82,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=15&lang=en-us"
  },
  {
    DateTime: "2018-09-29T16:00:00-04:00",
    EpochDateTime: 1538251200,
    WeatherIcon: 4,
    IconPhrase: "Intermittent clouds",
    IsDaylight: true,
    Temperature: { Value: 62.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 60.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 50.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 39.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 265, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 12.7, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 42,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 5000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 1,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 73,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=16&lang=en-us"
  },
  {
    DateTime: "2018-09-29T17:00:00-04:00",
    EpochDateTime: 1538254800,
    WeatherIcon: 4,
    IconPhrase: "Intermittent clouds",
    IsDaylight: true,
    Temperature: { Value: 61.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 58.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 49.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 39.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 273, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 12.7, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 44,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 5000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 1,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 64,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=17&lang=en-us"
  },
  {
    DateTime: "2018-09-29T18:00:00-04:00",
    EpochDateTime: 1538258400,
    WeatherIcon: 4,
    IconPhrase: "Intermittent clouds",
    IsDaylight: true,
    Temperature: { Value: 60.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 57.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 49.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 38.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 10.4, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 279, Localized: "W", English: "W" }
    },
    WindGust: { Speed: { Value: 12.7, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 45,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 30000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 1,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 51,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=18&lang=en-us"
  },
  {
    DateTime: "2018-09-29T19:00:00-04:00",
    EpochDateTime: 1538262000,
    WeatherIcon: 3,
    IconPhrase: "Partly sunny",
    IsDaylight: true,
    Temperature: { Value: 58.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 54.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 48.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 38.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 9.2, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 285, Localized: "WNW", English: "WNW" }
    },
    WindGust: { Speed: { Value: 12.7, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 48,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 30000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 39,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=19&lang=en-us"
  },
  {
    DateTime: "2018-09-29T20:00:00-04:00",
    EpochDateTime: 1538265600,
    WeatherIcon: 34,
    IconPhrase: "Mostly clear",
    IsDaylight: false,
    Temperature: { Value: 57.0, Unit: "F", UnitType: 18 },
    RealFeelTemperature: { Value: 53.0, Unit: "F", UnitType: 18 },
    WetBulbTemperature: { Value: 48.0, Unit: "F", UnitType: 18 },
    DewPoint: { Value: 39.0, Unit: "F", UnitType: 18 },
    Wind: {
      Speed: { Value: 9.2, Unit: "mi/h", UnitType: 9 },
      Direction: { Degrees: 291, Localized: "WNW", English: "WNW" }
    },
    WindGust: { Speed: { Value: 12.7, Unit: "mi/h", UnitType: 9 } },
    RelativeHumidity: 51,
    Visibility: { Value: 10.0, Unit: "mi", UnitType: 2 },
    Ceiling: { Value: 30000.0, Unit: "ft", UnitType: 0 },
    UVIndex: 0,
    UVIndexText: "Low",
    PrecipitationProbability: 0,
    RainProbability: 0,
    SnowProbability: 0,
    IceProbability: 0,
    TotalLiquid: { Value: 0.0, Unit: "in", UnitType: 1 },
    Rain: { Value: 0.0, Unit: "in", UnitType: 1 },
    Snow: { Value: 0.0, Unit: "in", UnitType: 1 },
    Ice: { Value: 0.0, Unit: "in", UnitType: 1 },
    CloudCover: 27,
    MobileLink:
      "http://m.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&lang=en-us",
    Link:
      "http://www.accuweather.com/en/ca/toronto/m5j/hourly-weather-forecast/55488?day=1&hbhhour=20&lang=en-us"
  }
];
